### ISSUE TITLE
problems with self-driving in dense traffic 

### ISSUE THREAD

**Issue by akielaries** [akielaries/cs386-a2.1#2]
problems with self-driving in dense traffic

**Comment by infinity3arc3** [comment]
The ability of the sensors in the vehicle is greatly hindered by dense traffic and vehicle colors, like zebra print. May need time to add pattern recognition.

**Comment by akielaries** [comment]
@infinity3arc3 please review

**Comment by infinity3arc3** [comment]
@BrockHeinz What do you think should be the focus in implementation of better pattern recognition
